### ISSUE TITLE
Stops searching on "space"

### ISSUE THREAD

**Issue by Shahroz16** [linkedin/Spyglass#16]
Hey There, thanks for this amazing library, i am facing this issue. 
Whenever I enter space, i don't get any thing in 
// public List<String> onQueryReceived(@NonNull QueryToken queryToken) {
How can i fix this? I need to cater space as a part of search. 
Thanks.

**Comment by nhibner** [comment]
The library uses the Tokenizer interface in determining how to parse the text input. Depending on your use case, you might just want to configure the WordTokenizer to parse up to 2 keywords (rather than the default 1). This means that the QueryToken returned in onQueryReceived may be one or two words long. You would need to modify your onQueryReceived to handle multiple keywords. Mentions in the LinkedIn app is configured in a similar manner. Here's an example:

```java
WordTokenizerConfig config = new WordTokenizerConfig.Builder().setMaxNumKeywords(2).build();
WordTokenizer tokenizer = new WordTokenizer(config);
editor.setTokenizer(tokenizer);
```

The other option is to implement your own Tokenizer which should allow you to achieve the exact behavior you would like.

**Comment by Shahroz16** [comment]
That was my first approach too but still 
    public List<String> onQueryReceived(@NonNull QueryToken queryToken) {
isn't notified when "space is entered".
So I thought maybe there is something i am missing.

**Comment by nhibner** [comment]
When you say "space is entered", do you mean literally just a space (as in, you only have " " in the EditText)? I assume that you mean that a space is entered after the user has typed something.

I tested the code that I wrote above by appending that code to the end of the onCreate method in the SimpleMentions.java sample and typing a city with two words (i.e. "Saint Louis"). Logging indicated that the onQueryReceived was called after I had typed "Saint " (note the space at the end).

Note that you may also need to decrease the threshold required before triggering suggestions for an implicit mention. By default, the threshold is set to 4, meaning that the query token must begin with 4 non-whitespace characters.

**Comment by Shahroz16** [comment]
Yes you assumed it right,and Threshold did the trick. 
I was searching like "a " and it would stop. 
Thanks a bunch. :D

**Comment by nhibner** [comment]
Great to hear that did the trick :)
