### ISSUE TITLE
how MentionSpan color change?

### ISSUE THREAD

**Issue by parkjaeiek** [linkedin/Spyglass#18]
how MentionSpan color change?

**Comment by nhibner** [comment]
Looking through the code, it appears to be quite a bit more difficult to change the color of the spans than I had expected. You would need to listen for when a mention is added, get the mention span, change the colors, and then rerender it. This is rather convoluted and inefficient.

Instead, would help if I provided custom XML attributes to set it on the views? I would also like to expose a factory so that you would be able to instantiate your own implementation of a MentionSpan upon insertion. If this would be an acceptable solution, I can jump on it and get it in as soon as possible.

**Comment by parkjaeiek** [comment]
ok...  I'll be expecting you.
