### ISSUE TITLE
How to genrate tags that can be shared over network. 

### ISSUE THREAD

**Issue by harminder-emobx-com** [linkedin/Spyglass#51]
Hello,

I have implemented this library in my android code, I want to share the tags over internet and want to show it on other end, Please suggest me  how to achieve this. I am using mention edit text. 

* is their any formatted output which can i use to generate tags on the other device.

**Comment by nhibner** [comment]
Hi,

This question has been asked in various forms already. Please see my comment on this issue: #35 

In general, this library does not handle persisting the tags to disk or over the internet. This was intentional, as depending on the app and use case, there are different ways in which the rich text would need to be represented. It is up to you to write the code that converts the spanned text into a format that can be written over the internet. See the above issue for a detailed example.

Hope that helps!

**Comment by harminder-emobx-com** [comment]
Hi @nhibner,

Thanks for a Quick response, I have read that is help full, I am having one issue.

Lets say i have a text with 1 mention and one simple text with same name eg 
nhibner this is a sample of my question @nhibner ,

In this case i have 2 matching for that name which will give me problem, 

Please suggest.

**Comment by nhibner** [comment]
From your example, the string will have the same name twice in the text, but only the second occurrence of the name will have a MentionSpan around it.
