### ISSUE TITLE
Display mentions list view after @ char on MentionEditText? by default it's showing for all text.

### ISSUE THREAD

**Issue by yogshinde** [linkedin/Spyglass#66]

**Comment by nhibner** [comment]
You can customize the behavior of when the mentions list displays by providing your own implementation of the Tokenizer interface. Many use cases can be handled by reusing the WordTokenizer implementation with a custom configuration.

Other than that, it's a bit hard to understand what your issue is when you have not provided much details. Please do not open issues if you are not going to provide adequate details on what the issue is.
