### ISSUE TITLE
Not able to post smilies

### ISSUE THREAD

**Issue by devrath** [linkedin/Spyglass#69]
When I post Smilies to another platform (**IOS**) from **RichEditor**. The smilies are not getting displayed on the **IOS**.

**Comment by nhibner** [comment]
@devrath It's a bit unclear to me how this library would impact the display of emoji, especially if they are displaying fine on Android. It sounds more like this is more of a compatibility issue between Android and iOS.

Closing this issue for now. If you can provide more details and explain why the issue is with this library, we can revisit.
